# Generated by Django 4.2.13 on 2024-06-16 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('CustomerID', models.CharField(max_length=512, primary_key=True, serialize=False)),
                ('Name', models.CharField(blank=True, max_length=512, null=True)),
                ('Email', models.CharField(blank=True, max_length=512, null=True)),
                ('ContactNumber', models.CharField(blank=True, db_column='Contact Number', max_length=512, null=True)),
                ('Address', models.CharField(blank=True, max_length=512, null=True)),
                ('Country', models.CharField(blank=True, max_length=512, null=True)),
                ('LastPurchaseDate', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'customers',
                'db_table': 'customers',
                'ordering': ['CustomerID'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('OrderID', models.CharField(max_length=512, primary_key=True, serialize=False)),
                ('OrderDate', models.DateField(blank=True, null=True)),
                ('TotalAmount', models.FloatField(blank=True, null=True)),
                ('ShippingAddress', models.CharField(blank=True, max_length=512, null=True)),
                ('CustomerID', models.ForeignKey(blank=True, db_column='CustomerID', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.customer')),
            ],
            options={
                'verbose_name_plural': 'orders',
                'db_table': 'orders',
                'ordering': ['OrderID'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('PaymentMethodID', models.AutoField(primary_key=True, serialize=False)),
                ('MethodType', models.CharField(blank=True, max_length=512, null=True)),
                ('Provider', models.CharField(blank=True, max_length=512, null=True)),
                ('CardNo', models.BinaryField(blank=True, null=True)),
                ('ExpiryDate', models.DateField(blank=True, null=True)),
                ('CVV', models.BinaryField(blank=True, null=True)),
                ('CustomerID', models.ForeignKey(blank=True, db_column='CustomerID', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.customer')),
            ],
            options={
                'verbose_name_plural': 'paymentmethods',
                'db_table': 'paymentmethods',
                'ordering': ['PaymentMethodID'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ProductID', models.CharField(max_length=512, primary_key=True, serialize=False)),
                ('ProductName', models.CharField(blank=True, max_length=512, null=True)),
                ('Category', models.CharField(blank=True, max_length=512, null=True)),
                ('UnitPrice', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'products',
                'db_table': 'products',
                'ordering': ['ProductID'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('TransactionID', models.AutoField(primary_key=True, serialize=False)),
                ('PaymentStatus', models.CharField(blank=True, max_length=512, null=True)),
                ('PaymentDate', models.DateField(blank=True, null=True)),
                ('Amount', models.FloatField(blank=True, null=True)),
                ('OrderID', models.ForeignKey(blank=True, db_column='OrderID', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.order')),
                ('PaymentMethodID', models.ForeignKey(blank=True, db_column='PaymentMethodID', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.paymentmethod')),
            ],
            options={
                'verbose_name_plural': 'transactions',
                'db_table': 'transactions',
                'ordering': ['TransactionID'],
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('OrderDetailID', models.AutoField(primary_key=True, serialize=False)),
                ('Quantity', models.IntegerField(blank=True, null=True)),
                ('UnitPrice', models.FloatField(blank=True, null=True)),
                ('OrderID', models.ForeignKey(blank=True, db_column='OrderID', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.order')),
                ('ProductID', models.ForeignKey(blank=True, db_column='ProductID', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
            ],
            options={
                'verbose_name_plural': 'orderdetails',
                'db_table': 'orderdetails',
                'ordering': ['OrderDetailID'],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StockQuantity', models.IntegerField(blank=True, null=True)),
                ('LastRestocked', models.DateField(blank=True, null=True)),
                ('ProductID', models.ForeignKey(db_column='ProductID', on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
            ],
            options={
                'verbose_name_plural': 'inventory',
                'db_table': 'inventory',
                'ordering': ['ProductID'],
            },
        ),
    ]
