# Generated by Django 4.2.13 on 2024-06-16 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_product_productdescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ProductDescription',
        ),
    ]
