# Generated by Django 4.2.13 on 2024-06-19 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Description',
            new_name='ProductDescription',
        ),
    ]
