# Generated by Django 4.2.13 on 2024-06-20 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_description_product_productdescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=255)),
                ('Password', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'users',
                'db_table': 'users',
                'ordering': ['UserID'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='UserID',
            field=models.ForeignKey(blank=True, db_column='UserID', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.users'),
        ),
    ]
