# Generated by Django 5.0.6 on 2024-06-21 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_users_order_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='LowStockAlerts',
            fields=[
                ('AlertID', models.AutoField(primary_key=True, serialize=False)),
                ('ProductID', models.CharField(max_length=255)),
                ('AlertDate', models.DateTimeField()),
                ('Message', models.CharField(max_length=255)),
                ('Processed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'LowStockAlerts',
                'db_table': 'LowStockAlerts',
                'ordering': ['AlertID'],
            },
        ),
        migrations.AlterField(
            model_name='users',
            name='Username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
