from django.urls import path
from . import views

urlpatterns = [
    path('', views.user_login, name='login'),
    path('dashboard/', views.index, name='index'),
    path('orders/', views.order_list, name='order_list'),
    # path('orders/<str:order_id>/', views.order_status, name='order_status'),
    path('orders/add/', views.order_create, name='order_create'),
    path('orders/<str:order_id>/', views.order_detail, name='order_detail'),
    path('orders/<str:order_id>/edit/', views.order_update, name='order_update'),
    path('orders/<str:order_id>/delete/', views.order_delete, name='order_delete'),
    path('products/', views.product_list, name='product_list'),
    path('products/add/', views.product_create, name='product_create'),
    path('products/<str:product_id>/', views.product_detail, name='product_detail'),
    path('products/<str:product_id>/edit/price/', views.product_update_price, name='product_update_price'),
    path('products/<str:product_id>/edit/description/', views.product_update_description, name='product_update_description'),
    path('products/<str:product_id>/delete/', views.product_delete, name='product_delete'),
    path('customers/', views.customer_list, name='customer_list'),
    path('customers/create/', views.customer_create, name='customer_create'),
    path('customers/<str:customer_id>/', views.customer_detail, name='customer_detail'),
    path('customers/<str:customer_id>/update/', views.customer_update, name='customer_update'),
    path('customers/<str:customer_id>/delete/', views.customer_delete, name='customer_delete'),
    path('inventory/', views.inventory_list, name='inventory_list'),
    path('inventory/<str:product_id>/update/', views.inventory_update, name='inventory_update'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.register, name='register'),
    path('api/getLowStockAlerts', views.get_low_stock_alerts, name='get_low_stock_alerts'),
    path('api/markAlertAsProcessed', views.mark_alert_as_processed, name='mark_alert_as_processed'),
    path('promotion/add/', views.add_promotion, name='add_promotion'),
    path('promotion/list/', views.list_promotion, name='list_promotion'),
    path('promotion/edit/<str:promotion_id>/', views.edit_promotion, name='edit_promotion'),
    path('promotion/delete/<str:promotion_id>/', views.delete_promotion, name='delete_promotion'),
     path('recommendation/add/', views.add_recommendation, name='add_recommendation'),
    path('recommendation/list/', views.list_recommendations, name='list_recommendations'),
    path('recommendation/edit/<str:recommendation_id>/', views.edit_recommendation, name='edit_recommendation'),
    path('recommendation/delete/<str:recommendation_id>/', views.delete_recommendation, name='delete_recommendation'),
    path('review/list/', views.list_reviews, name='list_reviews'),
    path('support_ticket/list/', views.list_support_tickets, name='list_support_tickets'),
    path('support_tickets/view/<str:ticket_id>/', views.view_ticket, name='view_ticket'),
    path('support_tickets/add_reply/<str:ticket_id>/', views.add_reply, name='add_reply'),
    path('support_tickets/resolve/<str:ticket_id>/', views.resolve_ticket, name='resolve_ticket'),
    
]
